# Generated by Django 5.0.2 on 2024-02-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('P', 'Paciente'), ('PR', 'Profesional')], max_length=2, null=True, verbose_name='tipo de usuario'),
        ),
    ]
