# Generated by Django 5.0.2 on 2024-03-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_birthday_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
