# Generated by Django 5.0.2 on 2024-04-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_session'),
        ('users', '0005_user_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.cityoption'),
        ),
    ]
