# Generated by Django 5.0.2 on 2024-02-15 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_care_physician', models.CharField(blank=True, max_length=255, null=True, verbose_name='Médico de Cabecera')),
                ('previous_therapy_experience', models.TextField(blank=True, null=True, verbose_name='Realizo terapia anteriormente')),
                ('reason_for_therapy', models.TextField(verbose_name='Motivo de la consulta')),
                ('therapy_schedule_preference', models.CharField(max_length=255, verbose_name='Preferencia horaria')),
                ('symptoms_description', models.TextField(verbose_name='Descripcion de Síntomas')),
                ('therapy_goals', models.TextField(verbose_name='Objetivos de la terapia')),
                ('therapist_gender_preference', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Preferencia de Terapeuta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
