# Generated by Django 5.0.2 on 2024-02-19 23:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_from_user', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenses_and_certifications', models.TextField(verbose_name='Licencias / Certificaciones')),
                ('therapeutic_approaches', models.TextField(verbose_name='Métodos utilizados en la terapia')),
                ('demographic_groups_served', models.TextField(verbose_name='Grupo demográfico atendido')),
                ('session_modalities', models.CharField(choices=[('In-person', 'Presencial'), ('Virtual', 'Virtual'), ('Both', 'Ambos')], max_length=50, verbose_name='Modalidad de la terapia')),
                ('availability', models.TextField(verbose_name='Disponibilidad horaria')),
                ('city_served', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
