# Generated by Django 5.0.2 on 2024-03-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='biography',
            field=models.CharField(blank=True, max_length=256, verbose_name='Breve biografía'),
        ),
        migrations.AddField(
            model_name='professional',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='city_served',
            field=models.CharField(max_length=100, verbose_name='Ciudad donde brinda atención'),
        ),
    ]
