# Generated by Django 5.0.2 on 2024-03-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_professional_biography_professional_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='licenses_and_certifications',
        ),
        migrations.AddField(
            model_name='professional',
            name='certifications_or_courses',
            field=models.TextField(blank=True, null=True, verbose_name='Certificaciones o Cursos Adicionales'),
        ),
        migrations.AddField(
            model_name='professional',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, verbose_name='Especialización'),
        ),
        migrations.AddField(
            model_name='professional',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título Obtenido'),
        ),
    ]
