# Generated by Django 5.0.2 on 2024-03-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_professional_licenses_and_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='biography',
            field=models.TextField(blank=True, max_length=256, verbose_name='Breve biografía'),
        ),
    ]
