# Generated by Django 5.0.2 on 2024-03-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_professional_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
