# Generated by Django 5.0.2 on 2024-03-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_professional_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='therapist_gender_preference',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'No tengo preferencia')], max_length=1, verbose_name='Preferencia de Terapeuta'),
        ),
    ]
