# Generated by Django 5.0.2 on 2024-03-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_patient_therapist_gender_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('morning', 'Mañana'), ('afternoon', 'Tarde'), ('night', 'Noche')], max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='professional',
            name='availability',
        ),
        migrations.AddField(
            model_name='professional',
            name='availability',
            field=models.ManyToManyField(related_name='professional', to='core.availabilityoption'),
        ),
    ]
