# Generated by Django 5.0.2 on 2024-03-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_groupoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupoption',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
