# Generated by Django 5.0.2 on 2024-04-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_groupoption_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='professional',
            name='city_served',
        ),
        migrations.AddField(
            model_name='professional',
            name='city_served',
            field=models.ManyToManyField(related_name='professional', to='core.cityoption'),
        ),
    ]
