# Generated by Django 5.0.2 on 2024-04-10 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_patient_professional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='Fecha de la sesión')),
                ('objectives', models.TextField(verbose_name='Objetivo trabajado')),
                ('difficulties', models.TextField(blank=True, null=True, verbose_name='Dificultades')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.professional')),
            ],
        ),
    ]
