# Generated by Django 5.0.4 on 2024-04-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_patient_professional_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofessionalconnection",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pendiente"), ("accepted", "Aceptado")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
